### ISSUE TITLE
launchWithCallback not firing the callback

### ISSUE THREAD

**Issue by toytonic** [wingify/vwo-react-native#4]
When calling 

`VWO.launchWithCallback`

the callback never gets fired neither with or without an error. Also the entire app will get unresponsive.

When using just `VWO.launch` it doesn't hang but I can't get any variation.

Thanks for your help.

**Comment by aman400** [comment]
You are running it on iOS or Android device?

**Comment by toytonic** [comment]
Hi, I tried it on Android.

**Comment by aman400** [comment]
Do you see any errors Logs?

**Comment by aman400** [comment]
fixed 22eda7581235784053d200c6941142cbc1e90919
